### ISSUE TITLE
Possible Python port?

### ISSUE THREAD

**Issue by MajikalExplosions** [kjoenth/To-Boldly-Go#16]
I'm not exactly sure how to code in QBasic, so I was wondering if I could get started on a Python port.  It's more like practice to me(I highly doubt that it would be able to run very well, knowing the amount of bugs I tend to have in programs), but maybe it could help with moving things to Python.

**Comment by seanth** [comment]
Yes, please. I'm much more comfortable with python than other languages. The major reason I have left things in QB64 is to insure there is a GUI version. I keep thinking something like a cherryPy implementation where the GUI is essentially a web page.

The template files are put together so that pythonic string replacements should Just Work™, and I've been making sure any comments can be converted easily from the ' QBAsic format to python's #

**Comment by MajikalExplosions** [comment]
Okay.  The only thing is that like I usually use Java, so I'm just going to write a Java port first for me to understand exactly what's going on before the Python port.

**Comment by tsal** [comment]
I've started taking a stab at this, I'm working from the ground up, implementing templating (simply) and then generation.

https://github.com/tsal/py-tbg

If you'd like to contribute, let me know and I'll gladly add @seanth or @MajikalExplosions

**Comment by tsal** [comment]
(or anyone else for that matter)

also, if I don't hear back from this closed issue in a few days, I'll open a new one and flag you both.

**Comment by MajikalExplosions** [comment]
Hi!  I believe @seanth has already started one in the branch snakes-on-a-plane.  I'm personally quite bad at Python, so I have basically just been reading what he's done up to this point.  

Side note: @seanth could you update the project page for the python port and add me and @tsal as collaborators(or something similar to that) to this repo?  Thanks!

**Comment by seanth** [comment]
Yeah, there's a start of the python port as the snakes-on-a-plane branch. It should generate galaxy file, but I have not validated anything yet. It also doesn't make planets yet.

**Comment by tsal** [comment]
Sorry it took me a while to see this - been in and out due to health issues, but I should be able to take a look at where the python stands over the weekend. I already stubbed out some template generation, but it may be something that I either throw away or see if it can fit here. 

Thanks!
