### ISSUE TITLE
Planet generated inside of parent star

### ISSUE THREAD

**Issue by Trainzack** [kjoenth/To-Boldly-Go#17]
The generated planets can sometimes have an orbital distance below the radius of their parent stars, making them inside the star. This example was found in a galaxy generated with TBG v0.3.1.2, and Kopernicus Release 1.6.1-1 running on KSP 1.6.1. I know that these versions are not supported by the galaxy generator, but since this has to do with the characteristics of the generated objects, I figure that this bug would still be present when running on the correct versions.
![screenshot21](https://user-images.githubusercontent.com/19575360/51305039-9426ea80-19ee-11e9-8203-8bd211efb895.png)
[Galaxygen_Info-Kipiricus.txt](https://github.com/kjoenth/To-Boldly-Go/files/2767672/Galaxygen_Info-Kipiricus.txt)

[galaxy.cfg.txt](https://github.com/kjoenth/To-Boldly-Go/files/2767673/galaxy.cfg.txt)

**Comment by MajikalExplosions** [comment]
@seanth Perhaps this is because the Roche limit calculations are wrong?  The code literally says `planet_distanceMin = star_RadiusKSP + INT(RND(1) * 100000000000) 'should be roche limit but isn't working`.  It *could* return a number less than the sun's radius.

**Comment by MajikalExplosions** [comment]
MakePlanets.bm lines 11 and 12 say:
`planet_distanceMin = simpleRocheLimit(star_MassKSP)*1000`
and
`planet_distanceMin = simpleRocheLimit(1.7565459e28)*1000`

@seanth is this intentional?

**Comment by seanth** [comment]
@MajikalExplosions: That hard coded value being fed into the roche limit function is almost certainly the bug. I _probably_ put Kerbol's mass in there as a hard coded test and just forgot to remove it 😊 

I'l looksie at your pull request

**Comment by MajikalExplosions** [comment]
Can we close this?

**Comment by kjoenth** [comment]
I want to leave #17 open until we test a bit more.

**Comment by seanth** [comment]
Pretty sure this is fixed.
